def build(bld):
    import os
    driver_node = bld.path.find_or_declare(
        'Gems/ScriptCanvas/Code/Include/ScriptCanvas/')
    gem_node = bld.path.find_or_declare('MyProject/Gem/Code')
    script_canvas_dir = driver_node.path_from(gem_node)

    AZ_CODEGEN_ARGS = az_code_gen = [{
                'files'   : [
                    'Source/ScriptCanvas/MyScriptCanvasNode.h',
                    'Source/ScriptCanvas/MyIncrementNode.h',
                ],
                'scripts' : [
                    os.path.join(script_canvas_dir,
                        'CodeGen/Drivers/ScriptCanvasNode.py')
                ]
            }]

    bld.DefineGem(
        # General
        includes                = ['.'],
        use                     = ['AzGameFramework',
                                   'MultiplayerCharacter',
                                   'ScriptCanvas'],
        disable_pch             = True,
        features                = ['az_code_gen'],
        az_code_gen             = AZ_CODEGEN_ARGS,


        # Platform Specific

        # ==============================
        # iOS
        # 'ios_output_file_name' must match both
        # 'executable_name' in 'project.json' and
        # 'Executable file' in '../Resources/IOSLauncher/Info.plist'
        # ==============================
        ios_output_file_name    = 'MyProjectLauncher',
        ios_file_list           = ['myproject_ios.waf_files'],

        # ==============================
        # AppleTV
        # 'appletv_output_file_name' must match both
        # 'executable_name' in 'project.json' and
        # 'Executable file' in '../Resources/AppleTVLauncher/Info.plist'
        # ==============================
        appletv_output_file_name = 'MyProjectLauncher',
        appletv_file_list       = ['myproject_appletv.waf_files'],

        darwin_file_list        = ['myproject_mac.waf_files'],

        restricted_script       = 'update_restricted_parameters',

        # Testing
        test_all_file_list      = ['myproject_tests.waf_files'],

        # Add additional custom build options here

    )
