
def build(bld):
    bld.DefineGem(
        # General
        includes                = ['.'],
        use                     = ['AzGameFramework'],
        disable_pch             = True,

        # Platform Specific

        # ==============================
        # iOS
        # 'ios_output_file_name' must match both
        # 'executable_name' in 'project.json' and
        # 'Executable file' in '../Resources/IOSLauncher/Info.plist'
        # ==============================
        ios_output_file_name    = 'MyProjectLauncher',
        ios_file_list           = ['myproject_ios.waf_files'],

        # ==============================
        # AppleTV
        # 'appletv_output_file_name' must match both
        # 'executable_name' in 'project.json' and
        # 'Executable file' in '../Resources/AppleTVLauncher/Info.plist'
        # ==============================
        appletv_output_file_name = 'MyProjectLauncher',
        appletv_file_list       = ['myproject_appletv.waf_files'],

        darwin_file_list        = ['myproject_mac.waf_files'],

        restricted_script       = 'update_restricted_parameters',

        # Testing
        test_all_file_list      = ['myproject_tests.waf_files'],

        # Add additional custom build options here

    )
